import { type BuildingDef, BuildingCategory, DensityLevel } from '@bitborough/core'

export const BUILDING_DEFS: Record<string, BuildingDef> = {
  // Zone buildings (auto-placed by simulation)
  'res.low': {
    id: 'res.low',
    category: BuildingCategory.Residential,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 10,
    jobs: 0,
    taxValue: 20,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.low': {
    id: 'com.low',
    category: BuildingCategory.Commercial,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 5,
    taxValue: 25,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.low': {
    id: 'ind.low',
    category: BuildingCategory.Industrial,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 10,
    taxValue: 15,
    pollutionRadius: 3,
    pollutionAmount: 10,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },

  // Player-placed buildings
  'power.coal': {
    id: 'power.coal',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 6,
    pollutionAmount: 20,
    powerRequired: false,
    roadRequired: false,
    cost: 3000,
    maintenanceCost: 120,
  },
  'power.nuclear': {
    id: 'power.nuclear',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: 5000,
    maintenanceCost: 250,
  },
  'service.police': {
    id: 'service.police',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 500,
    maintenanceCost: 100,
  },
  'service.fire': {
    id: 'service.fire',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 500,
    maintenanceCost: 100,
  },
  'special.park': {
    id: 'special.park',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: 10,
    maintenanceCost: 0,
  },
}
