import { type BuildingDef, BuildingCategory, DensityLevel, COSTS, MAINTENANCE } from '@bitborough/core'

export const BUILDING_DEFS: Record<string, BuildingDef> = {
  // Zone buildings (auto-placed by simulation)
  'res.low': {
    id: 'res.low',
    category: BuildingCategory.Residential,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 10,
    jobs: 0,
    taxValue: 20,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.low': {
    id: 'com.low',
    category: BuildingCategory.Commercial,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 5,
    taxValue: 25,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.low': {
    id: 'ind.low',
    category: BuildingCategory.Industrial,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 10,
    taxValue: 15,
    pollutionRadius: 3,
    pollutionAmount: 10,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },

  // --- MEDIUM DENSITY (auto-placed by simulation) ---
  'res.med': {
    id: 'res.med',
    category: BuildingCategory.Residential,
    density: DensityLevel.Medium,
    size: { w: 1, h: 1 },
    population: 100,
    jobs: 0,
    taxValue: 200,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'res.med.b': {
    id: 'res.med.b',
    category: BuildingCategory.Residential,
    density: DensityLevel.Medium,
    size: { w: 2, h: 1 },
    population: 120,
    jobs: 0,
    taxValue: 240,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.med': {
    id: 'com.med',
    category: BuildingCategory.Commercial,
    density: DensityLevel.Medium,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 30,
    taxValue: 150,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.med.b': {
    id: 'com.med.b',
    category: BuildingCategory.Commercial,
    density: DensityLevel.Medium,
    size: { w: 2, h: 2 },
    population: 0,
    jobs: 36,
    taxValue: 180,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.med': {
    id: 'ind.med',
    category: BuildingCategory.Industrial,
    density: DensityLevel.Medium,
    size: { w: 2, h: 2 },
    population: 0,
    jobs: 10,
    taxValue: 60,
    pollutionRadius: 4,
    pollutionAmount: 20,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.med.b': {
    id: 'ind.med.b',
    category: BuildingCategory.Industrial,
    density: DensityLevel.Medium,
    size: { w: 3, h: 2 },
    population: 0,
    jobs: 12,
    taxValue: 72,
    pollutionRadius: 4,
    pollutionAmount: 24,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },

  // --- HIGH DENSITY (auto-placed by simulation) ---
  'res.high': {
    id: 'res.high',
    category: BuildingCategory.Residential,
    density: DensityLevel.High,
    size: { w: 2, h: 2 },
    population: 330,
    jobs: 0,
    taxValue: 660,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.high': {
    id: 'com.high',
    category: BuildingCategory.Commercial,
    density: DensityLevel.High,
    size: { w: 2, h: 2 },
    population: 0,
    jobs: 175,
    taxValue: 875,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'com.high.b': {
    id: 'com.high.b',
    category: BuildingCategory.Commercial,
    density: DensityLevel.High,
    size: { w: 2, h: 3 },
    population: 0,
    jobs: 200,
    taxValue: 1000,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.high': {
    id: 'ind.high',
    category: BuildingCategory.Industrial,
    density: DensityLevel.High,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 5,
    taxValue: 150,
    pollutionRadius: 6,
    pollutionAmount: 40,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },
  'ind.high.b': {
    id: 'ind.high.b',
    category: BuildingCategory.Industrial,
    density: DensityLevel.High,
    size: { w: 4, h: 3 },
    population: 0,
    jobs: 6,
    taxValue: 180,
    pollutionRadius: 6,
    pollutionAmount: 48,
    powerRequired: true,
    roadRequired: true,
    cost: 0,
    maintenanceCost: 0,
  },

  // --- TRANSIT (player-placed) ---
  'transit.stop': {
    id: 'transit.stop',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 2, h: 2 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: COSTS.transitStop,
    maintenanceCost: MAINTENANCE.transitStop,
  },

  // Player-placed buildings
  'power.diesel': {
    id: 'power.diesel',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 2, h: 2 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 2,
    pollutionAmount: 5,
    powerRequired: false,
    roadRequired: false,
    cost: COSTS.dieselGenerator,
    maintenanceCost: MAINTENANCE.dieselGenerator,
  },
  'power.coal': {
    id: 'power.coal',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 6,
    pollutionAmount: 20,
    powerRequired: false,
    roadRequired: false,
    cost: COSTS.coalPlant,
    maintenanceCost: MAINTENANCE.coalPlant,
  },
  'power.nuclear': {
    id: 'power.nuclear',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: COSTS.nuclearPlant,
    maintenanceCost: MAINTENANCE.nuclearPlant,
  },
  'service.police': {
    id: 'service.police',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: COSTS.policeStation,
    maintenanceCost: MAINTENANCE.policeStation,
  },
  'service.fire': {
    id: 'service.fire',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: COSTS.fireStation,
    maintenanceCost: MAINTENANCE.fireStation,
  },
  'special.park': {
    id: 'special.park',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: COSTS.park,
    maintenanceCost: 0,
  },
}
