import { type BuildingDef, BuildingCategory, DensityLevel } from '@rcity/core'

export const BUILDING_DEFS: Record<string, BuildingDef> = {
  'power.coal': {
    id: 'power.coal',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 6,
    pollutionAmount: 20,
    powerRequired: false,
    roadRequired: false,
    cost: 3000,
    maintenanceCost: 120,
  },
  'power.nuclear': {
    id: 'power.nuclear',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 4, h: 4 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: 5000,
    maintenanceCost: 250,
  },
  'service.police': {
    id: 'service.police',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 500,
    maintenanceCost: 100,
  },
  'service.fire': {
    id: 'service.fire',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 3, h: 3 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: true,
    roadRequired: true,
    cost: 500,
    maintenanceCost: 100,
  },
  'special.park': {
    id: 'special.park',
    category: BuildingCategory.Special,
    density: DensityLevel.Low,
    size: { w: 1, h: 1 },
    population: 0,
    jobs: 0,
    taxValue: 0,
    pollutionRadius: 0,
    pollutionAmount: 0,
    powerRequired: false,
    roadRequired: false,
    cost: 10,
    maintenanceCost: 0,
  },
}
