import type { DocSection } from '../types.js'

export const budgetTaxes: DocSection = {
  id: 'budget-taxes',
  title: 'Budget & Taxes',
  body: [
    'Open the budget panel with **B**.',
    '',
    "**Income** comes from two sources: building taxes (based on each building's tax value) and land taxes (based on population and land values):",
    '',
    '`Tax Income = (Sum of Building Tax Values × Tax Rate) + (Population × Avg Land Value ÷ 40 × Tax Rate)`',
    '',
    "Buildings generate tax revenue as soon as they develop — you don't need a large population to start earning.",
    '',
    '**Tax Rate** — Default 7% (neutral). The demand system treats 7% as the baseline. Every 1% above or below shifts demand by ±5%:',
    '',
    '`Tax Modifier = 1.0 − (Tax Rate − 7%) × 5`',
    '',
    'Lower taxes boost demand but reduce income. Higher taxes suppress growth. Range: 0–20%.',
    '',
    '**Maintenance costs per month:**',
    '',
    '| Infrastructure | Cost |',
    '|---|---|',
    '| Roads | $0.50/tile |',
    '| Paved Roads | $1/tile |',
    '| Power Lines | $0.50/tile |',
    '| Diesel Generator | $15 |',
    '| Coal Plant | $60 |',
    '| Nuclear Plant | $100 |',
    '| Transit Stop | $50 |',
    '| Police Kiosk | $10 × (Funding ÷ 100) |',
    '| Police Station | $50 × (Funding ÷ 100) |',
    '| Fire Substation | $12 × (Funding ÷ 100) |',
    '| Fire Station | $50 × (Funding ÷ 100) |',
    '| School | $75 × (Funding ÷ 100) |',
    '| Small School | $15 × (Funding ÷ 100) |',
    '',
    '**Sprawl penalty:** When your city has a high building-footprint-to-population ratio, road and power line maintenance costs increase. Compact development with good population density avoids the penalty. Cities under 50 population are exempt.',
    '',
    "**Balance** is calculated and applied to your funds **each month**. If your funds run out, you can't build — but existing buildings continue to function.",
  ].join('\n'),
}
