import type { DocSection } from '../types.js'

export const zones: DocSection = {
  id: 'zones',
  title: 'Zones & Development',
  body: [
    'Zones are where your city grows. Place them and buildings appear automatically when conditions are met.',
    '',
    '**Requirements for initial development:**',
    '',
    '- Zone must be *powered*',
    '- Zone must be within *3 tiles of a road* (Manhattan distance)',
    '- Positive *demand* for that zone type',
    '',
    'Each month, every eligible empty zone tile rolls for development:',
    '',
    '`Development Chance = 12% × Zone Demand` — per tile per month',
    '',
    '**Density progression:** As your city grows, buildings automatically upgrade from Low → Medium → High density.',
    '',
    '- **Low → Medium:** Requires a *paved road* within 3 tiles and city population above 500. Buildings near the city center upgrade first.',
    '- **Medium → High:** Requires a *transit stop* within 10 tiles and a dense surrounding neighborhood. Clusters around transit hubs.',
    '',
    'Upgrades take *2 months* — you\'ll see a construction phase before the new building appears.',
    '',
    'If you remove infrastructure after an upgrade, the building goes *derelict*. Restore the infrastructure within 6 months to recover it, or it will downgrade.',
    '',
    '**Residential** — Where people live. Low: 10 pop. Medium: 100–120 pop. High: 330 pop.',
    '',
    '**Commercial** — Shops and offices. Demand scales with population. High density commercial generates exceptional tax revenue.',
    '',
    '**Industrial** — Factories. Higher density means *more production value but fewer jobs* due to automation — watch your unemployment.',
    '',
    'Watch the **R/C/I demand bars** in the top bar to know when to zone more.',
  ].join('\n'),
}
